spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/meuk?serverTimezone=UTC&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true&character_set_server=utf8mb4
    username: root
    password: 7447
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true